### ISSUE TITLE
12510 / Problema eseguibile diametrale 1,25

### ISSUE THREAD

**Issue by Faritech2022** [Diamond-SA/TB#2]
Verificare il motivo per il quale, se viene buildato EXE del progetto "Diametrale 1,25", lo stesso non comunica con il PLC

**Comment by Faritech2022** [comment]
Durante il build la cartella "DATA" non viene riempita.

Una volta inseriti i file nella cartella è tornato a funzionare correttamente

**Comment by simonemasa** [comment]
La qualità sta facendo il confronto tra la diametrale 1.25, e il laser manuale.
La settimana del 5 settembre bisognerà spostare la macchina in laboratorio in Diamond 1 (sotto terra), per effettuare delle prove.

Il reparto informatica installerà i programmi di microsoft.

**Comment by Faritech2022** [comment]
Ad oggi si è deciso di non installare il pacchetto office su questo PC.
La qualità ha effettuato le sue prove di rito, siamo in attesa di loro aggiornamenti

**Comment by Faritech2022** [comment]
Eseguibile funziona correttamente come da primo commento.
