### ISSUE TITLE
71170 / Inizializzazione Driver Sycotec

### ISSUE THREAD

**Issue by Etica27** [Diamond-SA/TB#26]
- [x] Verificare la nomenclatura  del software
- [x] Inizializzazione del Driver 
- [x] Consegna del Driver a MVT Port (verificare se necessaria una trasferta per rimontare anche gli assi lineari)

**Comment by polaeros** [comment]
23.08.22 (Intervento presso MVT, Simone M. e Eros P.)
Situarzione attuale:
Bohrmachine Nr.1: Alimentatore originale e Driver nuovo (parametri copiati da Driver originale Bohrmachine Nr. 2 ). Tutto funziona correttamente.
Bohrmachine Nr. 2: Alimentatore rotto, macchina ferma! Installato Driver originale (testato con alimentatore Bohrmachine Nr. 1).

MVT invia alimentatore Nr. 2 per riparazione e Driver Nr.1 per verifica.
