### ISSUE TITLE
27040 / Problema double TWIN

### ISSUE THREAD

**Issue by simonemasa** [Diamond-SA/TB#27]
Nella giornata di ieri il double twin ha smesso di funzionare, la causa è che si è bruciata una telecamera aca1300-30gm.

Siccome non disponiamo di quelle telecamere in accordo con il sig. Belli abbiamo deciso di "rubare" la telecamera montata sul twin in riparazione in TB per montarla sul double twin.

Richiesta l'offerta del prezzo e di delay alla sig.ra Cuni-Berzi.

- [x] Montare la telecamera e testare il funzionamento

**Comment by Faritech2022** [comment]
La telecamera Aca 1300-30gm, non viene più prodotta.

Il problema della macchina è stato risolto inserendo : 
- Pianino --> telecamera Aca2500-14gm
- Fibra --> telecamera Aca1300-30gm

Dalle prove effettuate, sembra che la telecamera Aca2500-14gm possa sopperire alla telecamera Aca1300-30gm.
