### ISSUE TITLE
71305 / Problema tagliofibra GmbH (Germania)

### ISSUE THREAD

**Issue by simonemasa** [Diamond-SA/TB#28]
Il taglio fibra in Germania dopo un po di tempo di utilizzo si spegne, e si riaccende facendo l'inizializzazione.
Da quanto ho potuto capire, sembra che l'alimentatore subisce un calo di tensione e faccia spegnere il PLC qualche ms.

è stato ordinato un nuovo alimentatore che verrà spedito alla GmbH.

**Comment by Faritech2022** [comment]
Problema risolto
