### ISSUE TITLE
14005 / Progetto e costruzione nuovo switch ottico

### ISSUE THREAD

**Issue by Faritech2022** [Diamond-SA/TB#3]
1) Ricerca e ordine componenti
2)	Ordinare switch sercalo
3) Innestare fibra ottica 
4) Preparare frontalino e retro macchina
5) Preparare scheda elettronica 
6) Preparare fondo macchina
7) Test in PFH

**Comment by Faritech2022** [comment]
task ad oggi terminati : 
1) Ricerca e ordine componenti
2) Ordinare switch sercalo
3) Innestare fibra ottica
4) Preparare frontalino e retro macchina
6) Preparare fondo macchina

Ancora da terminare : 
5) Preparare scheda elettronica
7) Test in PFH

**Comment by simonemasa** [comment]
Lo switch ottico che ci è stato fornito è guasto. Sto aspettando risposta per vedere come procedere per la restituzione.

**Comment by Faritech2022** [comment]
02/11/2022
Mescheri sta effettuando la restituzione dello switch

Siamo in attesa di un feedback da Sercalo

**Comment by Faritech2022** [comment]
Sercalo ci ha restituito lo switch, indicando che non è presente nessun malfunzionamento nello stesso.

Dal 03/2023, riprenderemo i lavori su tale progetto

**Comment by Faritech2022** [comment]
Non più necessario.

Reparto informatico ha chiuso attività
