### ISSUE TITLE
L-1000-14.49.49 / Verificare materiale per altre 2 DACA

### ISSUE THREAD

**Issue by simonemasa** [Diamond-SA/TB#38]
Bisogna verificare se il materiale elettrico/meccanico è a sufficienza per produrre altre 2 DACA.

**Comment by Faritech2022** [comment]
02/11/2022 Enea fa cernita materiale elettronico e meccanico per altre 2 macchina

**Comment by Faritech2022** [comment]
Da ordinare tutto materiale elettrico elettronico per altre 2 DACA
